### ISSUE TITLE
Repair Admin Module

### ISSUE THREAD

**Issue by pratik-restalgo** [RestAlgo/TradingApplication#115]
Repair Admin Module to run in blank database without error.
Start Date: 22-05-2024.

**Comment by Aman-Restalgo** [comment]
During the handling of blank data, we encountered a mapping data-related issue, which we resolved. An error in the branch map also emerged, which we successfully fixed. This error was due to a problem with the database. we checked and repaired all the forms related to the database to ensure everything was functioning correctly.

**Comment by Aman-Restalgo** [comment]
We are facing an error while installing the admin application and IIS that we were looking for today and trying to solve. In the end, we found out that there was an issue with the date time format which we have solved. We need to check if the date time error in the application is coming from this or from the admin.
