### ISSUE TITLE
Create new form for Exposure % Master

### ISSUE THREAD

**Issue by pratik-restalgo** [RestAlgo/TradingApplication#117]
Create new exposure % master in Trading Application

1. Read ael.csv file and load data in dictionary (defined in RYDTCommon) memory when trading application is logged in successfully.
2. Get symbol from csv file as dictionary key and MarginExposurePerMaster as value.
3. If instrument type in csv file is OTH then update OTH_Per property and is OTM then update in OTM_Per property in MarginExposurePerMaster class.
4. Display dictionary in virtual data grid view.
5. New row can be added or existing row can be edited on the form.
6. When "Save" button is pressed update in memory.

AEL sample file: [ael_28122023.csv](https://github.com/RestAlgo/TradingApplication/files/15415766/ael_28122023.csv)

**Comment by Usha-Restalgo** [comment]
Read ael.csv file and load data in dictionary (defined in RYDTCommon) memory when trading application is logged in successfully.-done
Get symbol from csv file as dictionary key and MarginExposurePerMaster as value.-done
If instrument type in csv file is OTH then update OTH_Per property and is OTM then update in OTM_Per property in MarginExposurePerMaster class.-done
Display dictionary in virtual data grid view.-done
New row can be added or existing row can be edited on the form.-done

**Comment by Usha-Restalgo** [comment]
Read ael.csv file and load data in dictionary (defined in RYDTCommon) memory when trading application is logged in successfully.
Get symbol from csv file as dictionary key and MarginExposurePerMaster as value.
If instrument type in csv file is OTH then update OTH_Per property and is OTM then update in OTM_Per property in MarginExposurePerMaster class.
Display dictionary in virtual data grid view.
New row can be added or existing row can be edited on the form.
When "Save" button is pressed update in memory.
Done all task tomorrow date 25-05-2024 
Due to little logic change it take a time to fulfill requirement 
So putting this task to Development done

**Comment by pratik-restalgo** [comment]
@Usha-Restalgo  madam, please update CheckPoint PDF for this point.

**Comment by Usha-Restalgo** [comment]
[FrmOrderHistoryCheckPoint.pdf](https://github.com/RestAlgo/TradingApplication/files/15469168/FrmOrderHistoryCheckPoint.pdf)
