### ISSUE TITLE
Branch can apply limit for it's child branch, dealers and clients only

### ISSUE THREAD

**Issue by pratik-restalgo** [RestAlgo/TradingApplication#319]
If 
B1 Branch is parent branch of B1A and B1B and D1 and D2 dealers and C1 and C2 clients are in B1A branch and D3 and D4 dealers and C3 and C4 clients are in B1B branch.
If B1 branch is logging in Admin Module then they can set limit for all branches (B1A, B1B), all Dealers (D1, D2, D3, D4) and all clients (C1, C2, C3, C4) in the Limit Master form.
If B1A branch is logging in Admin Module then they can set limit for D1 and D2 dealers and C1 and C2 dealers only in the limit master form.
If B1B branch is logging in Admin Module then they can set limit for D2 and D3 dealers and C2 and C3 dealers only in the limit master form.

**Comment by Aman-Restalgo** [comment]
this task don today 11 pm but pending discuss with lokesh sir

**Comment by Aman-Restalgo** [comment]
Done by lokesh sir

**Comment by Aman-Restalgo** [comment]
testing and merging a code old branch to new branch

**Comment by Aman-Restalgo** [comment]
done my side testing pending with ppb because of i am working on Number of branch license validation
[#343](https://github.com/RestAlgo/TradingApplication/issues/343)

[T_318&319_CheckPoint_AdminModule_24-07-2024.pdf](https://github.com/user-attachments/files/16357953/T_318.319_CheckPoint_AdminModule_24-07-2024.pdf)

**Comment by pratik-restalgo** [comment]
done
